In [1]:
import os
import seaborn as sns
path = '/Users/connormcdonald/Desktop/Masters/MIT807/Gartner Repository/Analysis/Figures'
import sys
sys.path.insert(1, '/Users/connormcdonald/Desktop/Masters/MIT807/Gartner Repository/Data Collection')
from configs import *
import numpy as np
import statsmodels.formula.api as smf
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt

from mpl_toolkits.axisartist.axislines import SubplotZero
from pylab import text
matplotlib.use("pgf")
matplotlib.rcParams.update({
    "pgf.texsystem": "lualatex",
    'font.family': 'serif',
    'text.usetex': True,
    'pgf.rcfonts': False,
})
import matplotlib.patches as mpatches

from sqlalchemy import create_engine

engine = create_engine('mysql+mysqlconnector://'+user+':'+passwd+'@'+ip+':3306/'+schema1)

In [2]:
stmt = '''SELECT DATE_FORMAT(date, \'%Y-%m\') as date, 
COUNT(1) AS tweets FROM social.blockchain
group by DATE_FORMAT(date, \'%Y-%m\') 
ORDER BY DATE_FORMAT(date, \'%Y-%m\') ASC'''

df = pd.read_sql(stmt, con=engine)

In [3]:
year = ['2010-01-01', '2010-12-31', '2011-12-31', '2012-12-31', '2013-12-31', '2014-12-31', '2015-12-31', '2016-12-31', '2017-12-31', '2018-12-31', '2019-12-31', '2020-12-31', '2021-12-31']
papers = [0,2, 0, 1, 2, 12, 41, 182, 824, 3027, 6040, 7988, 9917]

df['date']  = pd.to_datetime(df['date'])
year = pd.to_datetime(year)

In [5]:
#ML plot
ax = plt.gca()
ax.spines['right'].set_visible(False)
ax.spines['top'].set_visible(False)
plt.rcParams["figure.figsize"] = [8, 4]
plt.rcParams.update({'font.size': 12})
plt.rcParams['figure.dpi'] = 300
plt.xlabel('Time')
plt.ylabel('Number of Records')
plt.plot(df['date'], df['tweets'], c = '#E31B23', linewidth = 1, label='Tweets')
plt.legend()
plt.savefig(os.path.join(path, 'BC_data1.pdf'), format='pdf',bbox_inches='tight',pad_inches = 0)
plt.close()

In [5]:
#ML plot
ax = plt.gca()
ax.spines['right'].set_visible(False)
ax.spines['top'].set_visible(False)
plt.rcParams["figure.figsize"] = [8, 4]
plt.rcParams.update({'font.size': 12})
plt.rcParams['figure.dpi'] = 300
plt.xlabel('Time')
plt.ylabel('Number of Records')
plt.plot(year, papers, c = '#339898', linewidth = 1, label='Academic Publications')
plt.legend()
plt.savefig(os.path.join(path, 'BC_data2.pdf'), format='pdf',bbox_inches='tight',pad_inches = 0)
plt.close()

In [6]:
df_btc = pd.read_csv('/Users/connormcdonald/Desktop/Masters/MIT807/Gartner Repository/Bitcoin.csv')

In [7]:
df_btc = df_btc.replace(',','', regex=True)

In [8]:
from datetime import datetime


def mdy_to_ymd(d):
    return datetime.strptime(d, '%b %Y').strftime('%Y-%m-%d')


def to_year(d):
    return datetime.strptime(d, '%b %Y').strftime('%Y-%m-%d')

In [9]:
df_btc['Date'] = pd.to_datetime(df_btc['Date'].apply(mdy_to_ymd))
df_btc['Price'] = df_btc['Price'].astype(float)
df_btc

          Date    Price     Open     High      Low     Vol. Change %
0   2022-01-01  38498.6  46217.5  47944.9  32985.6    2.03M  -16.70%
1   2021-12-01  46219.5  56891.7  59064.3  42587.8    1.90M  -18.75%
2   2021-11-01  56882.9  61310.1  68990.6  53448.3    1.85M   -7.22%
3   2021-10-01  61309.6  43824.4  66967.1  43292.9    2.18M   39.90%
4   2021-09-01  43823.3  47129.2  52885.3  39646.8    2.21M   -7.02%
..         ...      ...      ...      ...      ...      ...      ...
133 2010-12-01      0.3      0.2      0.3      0.2  263.65K   44.09%
134 2010-11-01      0.2      0.2      0.5      0.1  826.25K    0.00%
135 2010-10-01      0.2      0.1      0.2      0.0    1.11M  210.99%
136 2010-09-01      0.1      0.1      0.2      0.1  216.81K    0.00%
137 2010-08-01      0.1      0.1      0.1      0.0  221.74K    0.00%

[138 rows x 7 columns]

In [15]:
ax = plt.gca()
ax.spines['right'].set_visible(False)
ax.spines['top'].set_visible(False)

plt.rcParams["figure.figsize"] = [8, 4]
plt.rcParams.update({'font.size': 12})
plt.rcParams['figure.dpi'] = 300
plt.xlabel('Time')
plt.ylabel('Price (USD)')
plt.plot(df_btc.Date, df_btc.Price, c = 'black', linewidth = 1, label='Bitcoin Price')
plt.savefig(os.path.join(path, 'bitcoin_price.pdf'), format='pdf',bbox_inches='tight',pad_inches = 0)
plt.close()

In [10]:
df.head()

        date  tweets
0 2011-03-01       1
1 2011-04-01       2
2 2011-05-01      11
3 2011-06-01      11
4 2011-07-01       6

In [11]:
df  = pd.merge(df,df_btc,left_on='date', right_on="Date", how="inner")

In [12]:
df_post = df[df.date>="2020-01-01"]
df_pre = df[df.date<"2020-01-01"]
df_post.head()

,date,tweets,Date,Price,Open,High,Low,Vol.,Change %
106,2020-01-01,212533,2020-01-01,9349.1,7196.4,9569.0,6884.1,23.56M,29.91%
107,2020-02-01,195335,2020-02-01,8543.7,9349.3,10482.6,8543.7,23.76M,-8.62%
108,2020-03-01,185968,2020-03-01,6412.5,8543.8,9180.8,3869.5,48.24M,-24.94%
109,2020-04-01,181805,2020-04-01,8629.0,6412.4,9437.5,6157.4,39.41M,34.56%
110,2020-05-01,197275,2020-05-01,9454.8,8628.6,10033.0,8235.6,38.48M,9.57%

In [13]:

column_1 = df_post["tweets"]
column_2 = df_post["Price"]
correlation = column_1.corr(column_2)


print(correlation)

0.7805736689780134

In [14]:

column_1 = df_pre["tweets"]
column_2 = df_pre["Price"]
correlation = column_1.corr(column_2)


print(correlation)

0.8316033221440029

In [15]:

column_1 = df["tweets"]
column_2 = df["Price"]
correlation = column_1.corr(column_2)


print(correlation)

0.5125906268175625

In [22]:
year = [2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021]
papers =  [0, 1, 2, 12, 41, 182, 824, 3027, 6040, 7988, 9917, 7225]
btc_annual = [0.3, 4.7, 13.5, 805.9, 318.2, 430.0, 963.4, 13850.4, 3709.4, 7196.4, 28949.4, 46219.5]

df2 = pd.DataFrame(year,columns =['year'])
df2['papers'] = papers
df2['price'] = btc_annual
df2

    year  papers    price
0   2010       0      0.3
1   2011       1      4.7
2   2012       2     13.5
3   2013      12    805.9
4   2014      41    318.2
5   2015     182    430.0
6   2016     824    963.4
7   2017    3027  13850.4
8   2018    6040   3709.4
9   2019    7988   7196.4
10  2020    9917  28949.4
11  2021    7225  46219.5

In [23]:
df_post =  df2.tail(2)
df_pre = df2.head(9)
df_post

    year  papers    price
10  2020    9917  28949.4
11  2021    7225  46219.5

In [24]:

column_1 = df_post["price"]
column_2 = df_post["papers"]
correlation = column_1.corr(column_2)


print(correlation)

-1.0

In [25]:

column_1 = df_pre["price"]
column_2 = df_pre["papers"]
correlation = column_1.corr(column_2)


print(correlation)

0.5651623724467901

In [26]:

column_1 = df2["price"]
column_2 = df2["papers"]
correlation = column_1.corr(column_2)


print(correlation)

0.7271874387801361

In [23]:
(0.415+0.414)/2

0.4145

In [2]:
def create(*x,crest1=50,crest2=25,stp_crest1=0.8,stp_crest2=0.2,midPoint=15,var=10):

    '''
    to create a Story HypeCycle
        x: Input data
        crest1,crest2: Controlling the height of the first wave crest and the second wave crest respectively.
        stp_crest1,stp_crest2: Representing steepness.
        midPoint: The location of the mean value mainly controls the location of the first wave crest.
        var: Displaying moves or penalties for midpoint
        Recommended parameters:crest1=50,crest2=25,stp_crest1=0.8,stp_crest2=0.2,midPoint=15,var=10
        x = np.linspace(0, 50, 5000)
    '''
    x = x
    # If user doesn't submit submit x, it will create a default DataSet.
    if x==():
        x = np.linspace(0, 70, 5000)
    else:
        x=x[0]

    lf_11 = crest1/(1+ np.exp( 1 * stp_crest1 * (x-midPoint-var)))
    lf_12 = crest1/(1+ np.exp( 1 * stp_crest1 * (x-midPoint)))
    lf_13 = crest2/(1+ np.exp( 1 * stp_crest2 * (x-midPoint-var)))
    hype= lf_11- lf_12- lf_13
    return hype

In [3]:
def annotate(*x, x_value = 20, text = "None",color = "red",fontproperties='FZShuTi', fontsize = 13, alpha = 0.8,rotation=3):

    """
     to annaotate the HypeCycle Curve
    """

    x = x
    # If user doesn't submit submit x, it will create a default DataSet.
    if x==():
        x = np.linspace(0, 70, 5000)
    else:
        x=x[0]

    plt.plot(x, create(x), linewidth=3)

    x_val = x_value
    t = text
    c = color
    fp= fontproperties
    fs = fontsize
    a = alpha

    plt.rcParams["figure.figsize"] = [12, 6]
    plt.scatter(x_val, create(x_val), color="blue")
    plt.text(x_val, create(x_val), t ,color=c,fontproperties= fp, fontsize=fs, alpha=a,rotation=rotation)

In [4]:
def visualize(*x, color="black", linewidth=1, linestyle="-"):

    """
     to visualize the HypeCycle Data into a HypeCycle Curve
    """
    x = x
    # If user doesn't submit submit x, it will create a default DataSet.
    if x==():
        x = np.linspace(0, 70, 5000)
    else:
        x=x[0]

    plt.plot(x, create(x), linewidth = linewidth, c = color,linestyle = linestyle, label='Hype Cycle')
    ax.plot(23.4, 24.7,'.', color = '#339898') #cryptocurrency
    ax.plot(29.4, -5.9,'.', color = '#FF9A00') #crypto exchange
    ax.plot(18.3, 26.7,'.', color = '#E31B23') #blockchain
    ax.plot(23.9, 21.7,'.', color = '#E31B23') #blockchain
    ax.plot(24.3, 18.7,'.', color = '#E31B23') #blockchain
    ax.plot(20.7, 30.5,'.', color = '#999999') #NFT

    plt.show()

In [7]:
x = np.linspace(0, 70, 5000)
# matplotlib.rcParams["text.usetex"] = True
plt.rcParams["figure.figsize"] = [8, 4]
plt.xlabel('Time', size = 12)
plt.ylabel('Expectations', size = 12)
plt.rcParams['figure.dpi'] = 300
ax = plt.gca()

ax.annotate('2014, 2015',
            xy=(24, 24.7), xycoords='data',
            xytext=(30,30), textcoords='data',
            size=11,  
            arrowprops=dict(arrowstyle="->"),
            horizontalalignment='left', verticalalignment='top')

ax.annotate('2015',
            xy=(29.4, -7), xycoords='data',
            xytext=(27,-15), textcoords='data',
            size=11,  
            arrowprops=dict(arrowstyle="->"),
            horizontalalignment='left', verticalalignment='top')

ax.annotate('2016',
            xy=(17.5, 26.7), xycoords='data',
            xytext=(12,28), textcoords='data',
            size=11,  
            arrowprops=dict(arrowstyle="->"),
            horizontalalignment='right', verticalalignment='top')

ax.annotate('2017',
            xy=(24.5, 21.75), xycoords='data',
            xytext=(32,25), textcoords='data',
            size=11,  
            arrowprops=dict(arrowstyle="->"),
            horizontalalignment='left', verticalalignment='top')


ax.annotate('2018',
            xy=(25, 18.5), xycoords='data',
            xytext=(30,19), textcoords='data',
            size=11,  
            arrowprops=dict(arrowstyle="->"),
            horizontalalignment='left', verticalalignment='top')


ax.annotate('2021',
            xy=(20.7, 31), xycoords='data',
            xytext=(15, 40), textcoords='data',
            size=11,  
            arrowprops=dict(arrowstyle="->"),
            horizontalalignment='left', verticalalignment='top')


ax.axes.xaxis.set_ticklabels([])
ax.axes.yaxis.set_ticklabels([])
ax.spines['right'].set_visible(False)
ax.spines['top'].set_visible(False)

blue = mpatches.Patch(color='#339898', label='Cryptocurrency')
red = mpatches.Patch(color='#E31B23', label='Blockchain')
green = mpatches.Patch(color='#999999', label='Non-fungible Tokens')
orange = mpatches.Patch(color='#FF9A00', label='Cryptocurrency Exchange')
plt.legend(handles=[blue, red, green, orange])


visualize(x,"blue",8)


plt.savefig(os.path.join(path, 'gartners_hype_cycle_bc.pdf'), format='pdf',bbox_inches='tight',pad_inches = 0)
plt.close()

<ipython-input-4-68c25e3d4ab7>:21: UserWarning: Matplotlib is currently using pgf, which is a non-GUI backend, so cannot show the figure.
  plt.show()